name: Instagib
description: Instagib Q3DM17 running with WebGL
dependencies:
  chronosgl:
    path: C:\Coding\Projekte\Privat\ChronosGL
  chronosal:
    path: C:\Coding\Projekte\Privat\ChronosAL
  bspparser:
    path: C:\Coding\Projekte\Privat\Q3MapConverter\Dart\BSPParser
  browser: any
