name: 'Instagib'
version: 0.6.0
description: Instagib game using WebGL, Dart and the map Q3DM17 - The Longest Yard from Quake3Arena.
author: rhulha java4life@gmail.com
homepage: https://github.com/rhulha/Instagib

environment:
  sdk: '2.10.5'

dev_dependencies:
  build_runner: 'any'
  build_web_compilers: 'any'


dependencies:
  chronosgl:
    path: C:\BackupYes\Coding\Projects\Private\ChronosGL\Dart\ChronosGL
  chronosal:
    path: C:\BackupYes\Coding\Projects\Private\ChronosGL\Dart\ChronosAL
  bspparser:
    path: C:\BackupYes\Coding\Projects\Private\ChronosGL\Dart\Instagib\BSPParser
  


